---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by steven.
--- DateTime: 2021/6/24 10:27
---
local a, b = 1, 2 -- a 的 值 是 1， b 的 值 是 2
local c, d = 1, 2, 3 -- c 的 值 是 1， d 的 值 是 2， 3 被 舍弃 了
local e, f = 1 -- e 的 值 是 1， f 的 值 是 nil
print(a,b,c,d,e,f)
print(' 1' + 1) -- 2
print(' 10' * 2) -- 20
print( 1 == '1') -- false, 二者 类型 不同， 不会 进行 自动 类型 转换
print({' a'} == {'a'}) -- false, 对于 表 类型 值 比较 的 是 二者 的 引用
print( 1 == tonumber(' 1'))
print(' 1' == tostring( 1))
print( 1 and 5) -- 5
print( 1 or 5) -- 1
print( not 0) -- false
print('' or 1) -- '' Lua 的 逻辑 操作 符 支持 短路， 也就是说
print(' hello' .. ' ' .. 'world!') -- 'hello world!'



